### PR TITLE
Fix #2528

### LINKED ISSUE #2528: Impossible to run forked node on latest HH version
**Steps to reproduce:**

1. `npm init -y`
2. `npx hardhat` and select to create a config file
3. `npm i hardhat`
4. `npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/<key>` as per https://hardhat.org/hardhat-network/guides/mainnet-forking.html#forking-from-mainnet

Output: `Error HH604: Error running JSON-RPC server: Expected 'isActivatedEIP' to only be called with 2930 or 1559`

Never had this error before. I can only assume this is some sort of problem with either the latest Hardhat or the latest Ethereumjs.

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR fixes #2528

### CODE REVIEW

File: packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts [hunk 1]
```diff
@@ -140,6 +140,34 @@ describe("Hardhat module", function () {
             impersonatedAddress
           );
         });
+
+        it.only("lets you impresonate a contract", async function () {
```
Comment (asafyish) [inline packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts:144]: Probably want to remove this .only when pushing.

Comment (fvictorio) [reply packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts]: Good catch @asafyish. Fixed.

File: packages/hardhat-core/src/internal/util/hardforks.ts [hunk 2]
```diff
@@ -1,5 +1,34 @@
...
+  // Homestead
+  2, 7, 8,
+  // Tangerine Whistle
+  150, 158,
+  // Spurious Dragon
+  155, 160, 161, 170,
+  // Byzantium
+  100, 140, 196, 197, 198, 211, 214, 649, 658,
+  // Constantinople
+  101, 105, 123, 145,
```
Comment (fvictorio) [inline packages/hardhat-core/src/internal/util/hardforks.ts:13]: Is this correct? According to ethereum.org, it should be:

```suggestion
  1014, 1052, 1234, 145,
```
