### PR TITLE
Use code 3 for JSON-RPC responses where there has been a revert

### LINKED ISSUE #8043: Use code 3 for JSON-RPC responses where there has been a revert
The shape of the response from the JSON-RPC API for a revert is not specified.
However, both `geth` and `anvil` returns this shape:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 3,
    "message": "execution reverted: custom error 0x8d6ea8be: ...\u0014something went wrong\u0000...",
    "data": "0x8d6ea8..."
  }
}
```

Hardhat 3 is returning:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": {
      "message": "Internal error"
    }
  }
}
```

Tooling, including viem assumes the geth/anvil shape. Hardhat should be updated to match it.

We should ensure that this doesn't lead to either viem or ethers loosing the error cause.

### PR DESCRIPTION
**Pull request by ChristopherDedominici**
Fixes: https://github.com/NomicFoundation/hardhat/issues/8043

### CODE REVIEW

File: packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts [hunk 1]
```diff
@@ -270,11 +278,12 @@ const _handleError = (error: Error): JsonRpcResponse => {
...
       message: error.message,
-      data: {
-        message: error.message,
-        txHash,
-        data: returnData,
-      },
+      // For revert errors (code 3), use the raw hex data to match geth/anvil format.
+      // For other errors, use the object format for backward compatibility.
+      data:
+        isRevertError && returnData !== undefined
```
Comment (ChristopherDedominici) [inline packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts]: When we match `geth/anvil` format, we lose `txHash`. Do we want to inject `txHash` anyway? This might be a bit confusing for users though

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts [hunk 2]
```diff
@@ -2,57 +2,43 @@ import type { Hex } from "viem";
...
- * @throws If no valid `0x` prefixed hex string revert data is found anywhere in the error chain.
+ * @throws If the error is not the expected viem revert error structure.
  */
 export function extractRevertError(error: unknown): {
   name: string;
   message: string;
   data: Hex;
 } {
-  ensureError(error);
+  ensureError(error, ContractFunctionExecutionError);
```
Comment (ChristopherDedominici) [inline packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: This change can probably be removed, but with the error code 3, the logic can be simplified. So I think it's a nice refactoring to have a cleaner code

File: packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts [hunk 3]
```diff
@@ -256,8 +257,15 @@ const _handleError = (error: Error): JsonRpcResponse => {
   const txHash = extractTxHash(error);
   const returnData = extractReturnData(error);
 
-  // In case of non-hardhat error, treat it as internal and associate the appropriate error code.
-  if (!ProviderError.isProviderError(error)) {
+  // Check if this is a revert error (code 3) matching the geth/anvil convention.
+  const isRevertError =
+    "code" in error &&
+    typeof error.code === "number" &&
+    error.code === SolidityError.CODE;
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts]: This was discussed offline, this is on purpose

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts [hunk 4]
```diff
@@ -2,57 +2,43 @@ import type { Hex } from "viem";
...
+ * in its `raw` property.
  *
- * @param error - The thrown Viem `Error` object, which may include a `data` field
- *                or nested `cause` errors carrying the revert data.
+ * @param error - The thrown viem `Error` object.
  * @returns The `0x` hex string representing the revert data.
  *
- * @throws If no valid `0x` prefixed hex string revert data is found anywhere in the error chain.
+ * @throws If the error is not the expected viem revert error structure.
  */
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/ebb6b1da575c7bc116c323562bf5763928248c98

File: packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/ebb6b1da575c7bc116c323562bf5763928248c98

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts [hunk 5]
```diff
@@ -2,57 +2,43 @@ import type { Hex } from "viem";
...
-    -- all the nested errors might contain a `cause` field */
-    current = current.cause as Error | undefined;
-  }
+  ensureError(cause, ContractFunctionRevertedError);
 
   assertHardhatInvariant(
-    dataReason !== undefined,
-    `No revert data found on error.\nError name: "${error.name}", message: ${error.message}`,
+    cause.raw !== undefined,
+    `Expected raw revert data on ContractFunctionRevertedError, but got none. Error: "${cause.message}"`,
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/ebb6b1da575c7bc116c323562bf5763928248c98

File: packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts [hunk 6]
```diff
@@ -10,6 +10,7 @@ import type WebSocket from "ws";
 import { ensureError } from "@nomicfoundation/hardhat-utils/error";
 import { isObject } from "@nomicfoundation/hardhat-utils/lang";
 
+import { SolidityError } from "../../network-manager/edr/stack-traces/stack-trace-solidity-errors.js";
 import {
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts:13]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/6e548602a245e4b150eccdde2884d398172f0dc8

File: packages/hardhat-viem-assertions/test/internal/assertions/revert/revert-error-chain.ts [hunk 7]
```diff
@@ -0,0 +1,168 @@
...
+
+import hardhatViemAssertions from "../../../../src/index.js";
+
+describe("revert error cause chain", () => {
+  describe("in-process hardhat network", () => {
+    let hre: HardhatRuntimeEnvironment;
+    let viem: HardhatViemHelpers;
+
+    useEphemeralFixtureProject("hardhat-project");
+
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-viem-assertions/test/internal/assertions/revert/revert-error-chain.ts]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/b8541211b7486f63d6d5d2ab24f5702f4f2c5352

File: packages/hardhat-viem/test/revert-error-chain.ts [hunk 8]
```diff
@@ -0,0 +1,168 @@
...
+        }
+
+        current = current.cause instanceof Error ? current.cause : undefined;
+      }
+
+      assert.ok(
+        errorWithCode3 !== undefined,
+        "Expected to find an error with code 3 in the cause chain",
+      );
+    });
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-viem/test/revert-error-chain.ts:171]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/b8541211b7486f63d6d5d2ab24f5702f4f2c5352

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts [hunk 9]
```diff
@@ -2,57 +2,43 @@ import type { Hex } from "viem";
 
 import { assertHardhatInvariant } from "@nomicfoundation/hardhat-errors";
 import { ensureError } from "@nomicfoundation/hardhat-utils/error";
-import { isPrefixedHexString } from "@nomicfoundation/hardhat-utils/hex";
+import {
```
Comment (alcuadrado) [inline packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: I don't get why this needs to be changed. I would have assumed that it was still working as expected.

If I revert the changes to this package, except for the `package.json`, the tests still pass.

File: packages/hardhat-viem/test/revert-error-chain.ts [hunk 10]
```diff
@@ -0,0 +1,176 @@
+import type { HardhatViemHelpers } from "@nomicfoundation/hardhat-viem/types";
```
Comment (alcuadrado) [inline packages/hardhat-viem/test/revert-error-chain.ts:1]: I think this tests should be present in `hardhat-viem`, not this package.

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts (hunk 2 above)
Comment (alcuadrado) [reply packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: I think the previous version feel more robust. It also doesn't force you to change the test in `packages/hardhat-viem-assertions/test/internal/assertions/revert/revert.ts`, which had more useful information in the previous version.

**Review by alcuadrado — CHANGES_REQUESTED** [review]

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts (hunk 2 above)
Comment (ChristopherDedominici) [reply packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/b5e2f69e57ff42b2f378c68b0d169435c9b2bd32

File: packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts (hunk 9 above)
Comment (ChristopherDedominici) [reply packages/hardhat-viem-assertions/src/internal/assertions/revert/extract-revert-error.ts]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/b5e2f69e57ff42b2f378c68b0d169435c9b2bd32

File: packages/hardhat-viem/test/revert-error-chain.ts (hunk 10 above)
Comment (ChristopherDedominici) [reply packages/hardhat-viem/test/revert-error-chain.ts:1]: Done here: https://github.com/NomicFoundation/hardhat/pull/8104/changes/5cb67abc861775da64f9697b1a81d93b7a4954b7

File: packages/hardhat-viem/test/revert-error-chain.ts [hunk 11]
```diff
@@ -0,0 +1,173 @@
...
+
+import { useEphemeralFixtureProject } from "@nomicfoundation/hardhat-test-utils";
+import { ensureError } from "@nomicfoundation/hardhat-utils/error";
+import { createHardhatRuntimeEnvironment } from "hardhat/hre";
+import {
+  ContractFunctionExecutionError,
+  ContractFunctionRevertedError,
+} from "viem";
+
+import hardhatViem from "@nomicfoundation/hardhat-viem";
```
Comment (alcuadrado) [inline packages/hardhat-viem/test/revert-error-chain.ts]:
```suggestion
import hardhatViem from "../src/index.js";
```

**Review by alcuadrado — APPROVED** [review]
left a tiny comment but LGTM

File: packages/hardhat-viem/test/revert-error-chain.ts (hunk 11 above)
Comment (alcuadrado) [reply packages/hardhat-viem/test/revert-error-chain.ts]: Importing your own package is fragile, depends on how the package manager lays out the `node_modules`, but it's not guaranteed to work.
