### PR TITLE
fix: pass all artifacts to edr when executing solidity tests

### LINKED ISSUE #6522: Solidity tests task is not passing non-test artifacts to EDR
### Feedback

The `getCode/getDeployedCode` cheatcodes require all the project's artifacts to be available. But Hardhat is only passing test artifacts to EDR, meaning that the code of non-test contracts (which are the ones you are most likely to want) cannot be accessed.

Reproduction:

```solidity
// contracts/Foo.sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

contract Foo {}
```

```solidity
// contracts/Foo.t.sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

import { Test } from "forge-std/Test.sol";
import { Foo } from "./Foo.sol";

contract FooTest is Test {
    function test() public {
        bytes memory barBytecode = vm.getCode("contracts/Foo.sol:Foo");
    }
}
```

This test will fail with "No matching artifact found". If you change the argument to `"contracts/Foo.t.sol:FooTest"` it does work.

### PR DESCRIPTION
**Pull request by galargh**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

Resolves #6522

In this PR, I ensure the `compile` task is executed before the test sources compilation in the `test solidity` task. I also ensure that all the artifacts present in the artifacts folder after these two compilations are passed over to EDR for the solidity tests execution.

Context: https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1743408250467489

### CODE REVIEW

File: v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts [hunk 1]
```diff
@@ -109,46 +98,75 @@ export async function getBuildInfos(
...
+
+    assertHardhatInvariant(
+      solcVersion !== undefined,
+      "solcVersion should not be undefined",
+    );
+
+    const id = {
+      name: artifact.contractName,
+      solcVersion,
+      source: artifact.sourceName,
```
Comment (galargh) [inline v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts:158]: I wonder what value should we use for npm artifacts here?

**Review by agostbiro — COMMENTED** [review]
Hey thanks for this PR!

I might be wrong, but I think we should change `task-action.ts:L67` to include all `*.sol` files not just `*.t.sol`, so that all the contracts in Solidity sources get built even if they aren't part of the dependency graph of a test file. The reason for this is that users could try to load them with the `getCode/getDeployedCode` cheatcodes.

File: v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts [hunk 2]
```diff
@@ -49,6 +49,8 @@ const runSolidityTests: NewTaskActionFunction<TestActionArguments> = async (
     return;
   }
 
+  await hre.tasks.getTask("compile").run();
```
Comment (galargh) [inline v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts:52]: > I might be wrong, but I think we should change task-action.ts:L67 to include all *.sol files not just *.t.sol, so that all the contracts in Solidity sources get built even if they aren't part of the dependency graph of a test file. The reason for this is that users could try to load them with the getCode/getDeployedCode cheatcodes.

@agostbiro I'll reply here because this line is why the one you mentioned is correct. So what will be happening in the task after the changes introduced in this PR is:
1. We compile all the sources, excluding the test sources. We do that by calling the compile task. We don't compile the sources together with the test sources because we want the user to be able to use different build options for this step.
2. We compile all the test sources using the test build options.
3. We collect everything from artifacts folder to pass it to EDR. These include compilation artifacts from 1. and 2.
4. We find the test suite IDs that we want to pass to EDR. We do that by looking at all the artifacts and checking if:
  a. the source of the artifact matches one of the requested test sources
  b. the artifact contains any tests.
5. We pass 3. and 4. to EDR for the test execution.

Comment (agostbiro) [reply v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts:52]: Ah thanks for the explanation, sounds good! Could you add the first two points as comments?

**Review by agostbiro — APPROVED** [review]

File: v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts (hunk 2 above)
Comment (galargh) [reply v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts:55]: Of course, done :)

File: v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts [hunk 3]
```diff
@@ -49,6 +49,11 @@ const runSolidityTests: NewTaskActionFunction<TestActionArguments> = async (
     return;
   }
 
+  // NOTE: We run the compile task first to ensure all the artifacts for them are generated
+  // Then, we compile just the test sources. We don't do it in one go because the user
+  // is likely to use different compilation options for the tests and the sources.
+  await hre.tasks.getTask("compile").run();
```
Comment (alcuadrado) [inline v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts:55]: I think we need to reintroduce the `--no-compile` here, otherwise running `hardhat test` will compile twice.

File: v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts (hunk 1 above)
Comment (alcuadrado) [reply v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts:158]: It should be the `artifact.inputSourceName`, otherwise EDR won't find it.

We should polish the `sourceName` vs `inputSourceName` vs `publicSourceName` situation.

Comment (alcuadrado) [reply v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts:158]: but for now, something like `artifact.inputSourceName ?? artifact.sourceName`.

**Review by alcuadrado — CHANGES_REQUESTED** [review]
Left two comments, otherwise it looks good to me.

**Review by alcuadrado — APPROVED** [review]
🚀
