### PR TITLE
Fix deletion of valid build-info file

### LINKED ISSUE #1117: hardhat-etherscan breaks on hardhat/console.sol
when running 

```
npx hardhat verify --network mainnet
```

i was getting the error

```
[Error: ENOENT: no such file or directory, open '/Users/lev/dev/ldub/token-2/artifacts/build-info/4e7389b25e253b27f945b011dc8f896b.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/lev/dev/ldub/token-2/artifacts/build-info/4e7389b25e253b27f945b011dc8f896b.json'
}
```

this was being thrown by `const buildInfo = await artifacts.getBuildInfo(fqName);` on line https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-etherscan/src/solc/bytecode.ts#L97 when `fqName` was `hardhat/console.sol:console`. 

i added

```
if (fqName === "hardhat/console.sol:console") continue
```

in `token-2/node_modules/@nomiclabs/hardhat-etherscan/dist/src/solc/bytecode.js` and then the script verified just fine 

I am new to hardhat and dont know the root cause of why its even looking at the console but i hope this is sufficient information for @ItsNickBarry or someone else to fix :)

Thanks for the awesome tools all!

### PR DESCRIPTION
**Pull request by schaable**
Bug reproduction steps:

1. Create a contract that imports a dependency (can be local or external).
2. Compile the project.
3. Rename the contract, only changing the contract name (filename remains the same).
4. Compile again without using `--force` or `hh clean`.
5. Go to the artifacts folder. The debug file of the renamed contract will reference a valid build-info file. However, the imported dependency's debug file will point to a missing build-info file.

This issue occurs because the renamed contract is recompiled while the imported contract remains unchanged (which is correct). However, during the artifact cleanup, the original build-info file, which is still pointed by the imported contract, is mistakenly deleted. Two possible fixes are:

1. Ensure that every debug file points to the correct build-info file by adjusting the debug file pointers.
2. **Modify the cleanup process to delete build-info files only if they are not associated with any debug files. Although this fix was partially implemented, the build-info files were unintentionally deleted along with the invalid artifacts in `_removeArtifactFiles`.**

Closes #1117

### CODE REVIEW

File: packages/hardhat-core/test/builtin-tasks/compile.ts [hunk 1]
```diff
@@ -844,4 +844,96 @@ Read about compiler configuration at https://hardhat.org/config
...
+      const buildInfoPathE = path.join(
+        "artifacts",
+        "contracts",
+        "E.sol",
+        "E.dbg.json"
+      );
+      assertBuildInfoExists(buildInfoPathE);
+    });
+
+    afterEach(() => {
```
Comment (fvictorio) [inline packages/hardhat-core/test/builtin-tasks/compile.ts:927]: I think I'd slightly prefer to do this in the tests themselves, because they are the ones doing this change so it makes sense that they also do the cleanup. An `afterEach` that performs a cleanup of something that wasn't done in a `beforeEach` feels a bit weird to me.

I understand that this means the files won't be reverted if the test fails, but I'm ok with that trade-off.

**Review by fvictorio — APPROVED** [review]
Pre-approved because the comments I left are very minor. Feel free to ignore the one about the `afterEach` if you don't agree. The other one about removing the unnecessary import seems a bit more important.

File: packages/hardhat-core/test/builtin-tasks/compile.ts (hunk 1 above)
Comment (schaable) [reply packages/hardhat-core/test/builtin-tasks/compile.ts:927]: Yeah, my main worry was something failing during the test and breaking future runs. But it's ok if you're good with the trade-off.

File: packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/E.sol [hunk 2]
```diff
@@ -0,0 +1,6 @@
+// SPDX-License-Identifier: UNLICENSED
+pragma solidity 0.8.19;
+
+import "dependency/contracts/console.sol";
```
[the remark this answers is not in the document]
Comment (schaable) [reply packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/E.sol:4]: Good catch.
