### PR TITLE
Make node:test sequential by default

### LINKED ISSUE #8125: Make `node:test` sequential by default
Our `node:test` plugin runs in parallel by default, but that can have unexpected performance hits, and is inconsistent with the mocha plugin. We should switch it to be sequential by default.

In a follow up effort we'll add `--parallel` flags to both plugins.

### PR DESCRIPTION
**Pull request by ChristopherDedominici**
Fixes: https://github.com/NomicFoundation/hardhat/issues/8125

Docs do not need updateds in the `website` repo, as there are no references to `node:test` being executed in parallel.

Manual test ran in `example-project` to validate everything works as expected:
- pnpm hardhat test nodejs
- pnpm hardhat test nodejs --coverage 
- pnpm hardhat test nodejs --gasStats

### CODE REVIEW

**Comment by alcuadrado** [comment]
@schaable can you review this one as you have more context about coverage and gas stats?

**Comment by alcuadrado** [comment]
Also snapshots

File: packages/hardhat-node-test-runner/src/task-action.ts [hunk 1]
```diff
@@ -114,7 +114,7 @@ const testWithHardhat: NewTaskActionFunction<TestActionArguments> = async (
     const nodeTestOptions: LastParameter<typeof run> = {
       files,
       only,
-      concurrency: true, // uses `os.availableParallelism() - 1`
```
Comment (alcuadrado) [inline packages/hardhat-node-test-runner/src/task-action.ts:116]: I think we also need `isolation: "none"` to match Mocha's behavior. See: https://nodejs.org/api/test.html#runoptions

Comment (alcuadrado) [reply packages/hardhat-node-test-runner/src/task-action.ts:116]: And that's what may impact the integrations the most. /cc @schaable

Comment (ChristopherDedominici) [reply packages/hardhat-node-test-runner/src/task-action.ts:116]: I'll add `isolation=none` and see if tests in the CI pass as a first quick dirty test, then I'll investigate more on the actual impact

File: packages/hardhat-node-test-runner/src/task-action.ts [hunk 2]
```diff
@@ -114,7 +114,8 @@ const testWithHardhat: NewTaskActionFunction<TestActionArguments> = async (
...
+      concurrency: false,
+      isolation: "none",
     };
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-node-test-runner/src/task-action.ts:95]: `isolation: "none"` is already exercised by the existing integration tests that spawn real Hardhat CLI processes.

File: .changeset/strange-books-explode.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@nomicfoundation/hardhat-node-test-runner": patch
+---
+
+Make `node:test` sequential by default.
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply .changeset/strange-books-explode.md]: Done here: https://github.com/NomicFoundation/hardhat/pull/8142/changes/22a7093c7333732938c9c09bd9030fe88510ccdd

File: packages/hardhat-node-test-runner/test/helpers/run-hardhat.ts [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+  child.stderr.on("data", (chunk: string) => {
+    stderr += chunk;
+  });
+
+  const exitCode = await new Promise<number | null>((resolve, reject) => {
+    child.once("error", reject);
+    child.once("close", (code) => {
+      resolve(code);
+    });
+  });
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-node-test-runner/test/helpers/run-hardhat.ts:98]: Won't fix. Node's node `--test` runner already enforces a default per-test timeout. If the child process hangs, the outer test will be killed by that mechanism. Adding a redundant timeout inside this helper would just duplicate that responsibility with extra cleanup complexity for no real benefit.

File: packages/hardhat-node-test-runner/src/task-action.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-node-test-runner/src/task-action.ts:95]: No longer valid

File: packages/hardhat-node-test-runner/src/task-action.ts [hunk 5]
```diff
@@ -88,33 +87,21 @@ const testWithHardhat: NewTaskActionFunction<TestActionArguments> = async (
...
-    const testWorkerDone = new URL(
-      import.meta.resolve(
-        "@nomicfoundation/hardhat-node-test-runner/test-worker-done",
-      ),
-    );
-    imports.push(testWorkerDone.href);
-  }
+    hre.globalOptions.gasStatsJson !== undefined;
 
-  process.env.NODE_OPTIONS = imports
```
Comment (ChristopherDedominici) [inline packages/hardhat-node-test-runner/src/task-action.ts:108]: Since everything now is executed in the same process, there is no need to pass to subprocesses the info

File: packages/hardhat-node-test-runner/src/task-action.ts [hunk 6]
```diff
@@ -88,33 +87,21 @@ const testWithHardhat: NewTaskActionFunction<TestActionArguments> = async (
...
+  }
 
   async function runTests(): Promise<TestSummary> {
     const nodeTestOptions: LastParameter<typeof run> = {
       files,
       only,
-      concurrency: true, // uses `os.availableParallelism() - 1`
+      concurrency: false,
+      isolation: "none",
     };
```
[the remark this answers is not in the document]
Comment (ChristopherDedominici) [reply packages/hardhat-node-test-runner/src/task-action.ts:96]: Adding a fixture that deterministically detects parallel vs sequential execution would be fairly complex for the value it provides. The `concurrency: false` flag is a single, straightforward line that's unlikely to be accidentally removed or changed

File: packages/hardhat-node-test-runner/src/task-action.ts [hunk 7]
```diff
@@ -192,6 +170,13 @@ const testWithHardhat: NewTaskActionFunction<TestActionArguments> = async (
 
   const testResults = await runTests();
 
+  await hre.hooks.runHandlerChain(
```
Comment (ChristopherDedominici) [inline packages/hardhat-node-test-runner/src/task-action.ts:172]: Same approach as in mocha test runner

File: packages/hardhat-node-test-runner/src/task-action.ts [hunk 8]
```diff
@@ -88,33 +87,12 @@ const testWithHardhat: NewTaskActionFunction<TestActionArguments> = async (
...
-  imports.push(tsx.href);
-
-  if (
-    hre.globalOptions.coverage === true ||
-    hre.globalOptions.gasStats === true ||
-    hre.globalOptions.gasStatsJson !== undefined
-  ) {
-    const testWorkerDone = new URL(
-      import.meta.resolve(
-        "@nomicfoundation/hardhat-node-test-runner/test-worker-done",
```
Comment (schaable) [inline packages/hardhat-node-test-runner/src/task-action.ts:102]: I believe you also need to remove the `/test-worker-done` export in the package.json and the `packages/hardhat-node-test-runner/src/test-worker-done.ts` as they were only used here.

**Review by schaable — APPROVED** [review]
LGTM. Pre-approving.

File: packages/hardhat-node-test-runner/src/task-action.ts (hunk 8 above)
Comment (alcuadrado) [reply packages/hardhat-node-test-runner/src/task-action.ts:102]: let's not remove it, because older versions of the plugin will break

Comment (alcuadrado) [reply packages/hardhat-node-test-runner/src/task-action.ts:102]: oh, this is the plugin itself, not hardhat

Comment (schaable) [reply packages/hardhat-node-test-runner/src/task-action.ts:102]: Yes, it's used by the plugin itself so it should be safe

Comment (ChristopherDedominici) [reply packages/hardhat-node-test-runner/src/task-action.ts:102]: Done here: https://github.com/NomicFoundation/hardhat/pull/8142/changes/33e5b9184fc3bf8f40113be7708fad2851f9d108
