### PR TITLE
[HHV2] handle invalid Solidity cache JSON

### LINKED ISSUE #6489: Remove `solidity-files-cache.json` file if it's broken
Reported by @shark0der.

If the `cache/solidity-files-cache.json` file is broken (in his case it was because it was empty, which is an invalid JSON), then compilation fails.

When reading that file, we should detect if it's broken and remove it, which I think can always be done without issues.

### PR DESCRIPTION
**Pull request by iosh**
- [x] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

Ignore parsing errors in solidity-files-cache.json so compilation no longer stalls; fall  back to the default cache whenever the file is invalid.
resolve #6489

### CODE REVIEW

File: packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts [hunk 1]
```diff
@@ -53,12 +53,17 @@ export class SolidityFilesCache {
...
   ): Promise<SolidityFilesCache> {
-    let cacheRaw: Cache = {
+    const defaultCache: Cache = {
       _format: FORMAT_VERSION,
       files: {},
     };
+    let cacheRaw = defaultCache;
     if (await fsExtra.pathExists(solidityFilesCachePath)) {
-      cacheRaw = await fsExtra.readJson(solidityFilesCachePath);
+      try {
```
Comment (michalbrabec) [inline packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts:63]: `fsExtra.readJson` can throw multiple different types of errors (file not found, path is a directory, syntax error ...), we should not flatly absorb all of them and quietly ignore them.
I would propose:
- add a check to the `if` that `solidityFilesCachePath` is a file
-  catch all exceptions
    - do `cacheRaw = defaultCache;`
    - report any error to the terminal, except the syntax error (broken JSON or empty file)
      > not rethrow, just print the message

File: packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts [hunk 2]
```diff
@@ -53,12 +53,34 @@ export class SolidityFilesCache {
...
+
+        if (!cacheStats.isFile()) {
+          console.warn(
+            `Hardhat couldn't read the solidity files cache at ${solidityFilesCachePath} because it's not a file. Please remove it.`
+          );
+        } else {
+          cacheRaw = await fsExtra.readJson(solidityFilesCachePath);
+        }
+      } catch (error) {
+        cacheRaw = defaultCache;
```
Comment (michalbrabec) [inline packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts]: Nit: this is not necessary since the default cache is already assigned on the line 60 and any failure in `fsExtra.readJson` prevents assignment.

File: packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts [hunk 3]
```diff
@@ -53,12 +53,34 @@ export class SolidityFilesCache {
...
+        if (!(error instanceof SyntaxError)) {
+          const errorMessage =
+            error instanceof Error ? error.message : String(error);
+
+          console.warn(
+            `Hardhat couldn't read the solidity files cache at ${solidityFilesCachePath}: ${errorMessage}`
```
Comment (michalbrabec) [inline packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts]: Nit: Could be shorten as `Hardhat couldn't read the solidity files cache at ${solidityFilesCachePath}: ${error.message ?? String(error)}`. The `errorMessage ` could be then removed. Tested with:
```typescript
try {
  throw Error("test");
} catch (error: any) {
  console.log(error.message ?? String(error))
}
```

File: packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts [hunk 4]
```diff
@@ -53,12 +53,34 @@ export class SolidityFilesCache {
...
       files: {},
     };
+    let cacheRaw = defaultCache;
+
     if (await fsExtra.pathExists(solidityFilesCachePath)) {
-      cacheRaw = await fsExtra.readJson(solidityFilesCachePath);
+      try {
+        const cacheStats = await fsExtra.stat(solidityFilesCachePath);
+
+        if (!cacheStats.isFile()) {
```
Comment (michalbrabec) [inline packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts]: Nit: Could be shortened as `if ((await fsExtra.stat(solidityFilesCachePath)).isFile()) {`

**Review by michalbrabec — APPROVED** [review]

File: packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts [hunk 5]
```diff
@@ -53,12 +54,34 @@ export class SolidityFilesCache {
...
     };
+    let cacheRaw = defaultCache;
+
     if (await fsExtra.pathExists(solidityFilesCachePath)) {
-      cacheRaw = await fsExtra.readJson(solidityFilesCachePath);
+      try {
+        if ((await fsExtra.stat(solidityFilesCachePath)).isFile()) {
+          cacheRaw = await fsExtra.readJson(solidityFilesCachePath);
+        } else {
+          console.error(
```
Comment (michalbrabec) [inline packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts]: Delete the directory, without throwing errors, in the catch block.

File: packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts [hunk 6]
```diff
@@ -53,12 +54,34 @@ export class SolidityFilesCache {
...
+            picocolors.red(
+              `Hardhat couldn't read the solidity files cache at ${solidityFilesCachePath} because it's not a file. Please remove it.`
+            )
+          );
+        }
+      } catch (error) {
+        if (!(error instanceof SyntaxError)) {
```
Comment (michalbrabec) [inline packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts]: Do not show any error messages, print a debug message instead, for all errors (no if needed).
Debug message for inspiration [config-loading.ts](https://github.com/NomicFoundation/hardhat/blob/ab394ff047caa23a11af07aa886023d788deb3e7/v-next/hardhat/src/internal/config-loading.ts#L41)
Delete the file if it is malformed (parsing fails) or directory (since it is a directory and not a cache file).

File: .changeset/stupid-lions-know.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
+---
+"hardhat": patch
+---
+
+Ignore malformed solidity-files-cache so compilation keeps running while logging the issue in debug.
```
Comment (kanej) [inline .changeset/stupid-lions-know.md]:
```suggestion
Ignore malformed solidity-files-cache so compilation keeps running while logging the issue in debug ([#6489](https://github.com/NomicFoundation/hardhat/issues/6489))
```

**Review by kanej — APPROVED** [review]
