### PR TITLE
Fix warning: passing args to `spawn` when shell is set to true

### LINKED ISSUE #6896: Avoid `[DEP0190] DeprecationWarning` during project init on Node 24
If you initialize a project in Node 24 you get `[DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.`. We want to remove this deprecation warning.

The following approach appears to work:

```
import { spawn } from "node:child_process";

// Prints de deprecation warning
spawn("node", ["--version"], { stdio: "inherit" });

// Doesn't print it
spawn("node --version", { shell: true, stdio: "inherit" });
```

### PR DESCRIPTION
**Pull request by antico5**
Closes #6896

### CODE REVIEW

File: v-next/hardhat/src/internal/cli/init/init.ts [hunk 1]
```diff
@@ -469,7 +473,7 @@ export async function installProjectDependencies(
       console.log();
       console.log(commandString);
 
-      await spawn(command[0], command.slice(1), {
+      await spawn([command[0], ...command.slice(1)].join(" "), [], {
```
Comment (schaable) [inline v-next/hardhat/src/internal/cli/init/init.ts]:
```suggestion
      await spawn(commandString, [], {
```

File: v-next/hardhat/src/internal/cli/init/init.ts [hunk 2]
```diff
@@ -513,7 +517,7 @@ export async function installProjectDependencies(
...
```
Comment (schaable) [inline v-next/hardhat/src/internal/cli/init/init.ts]:
```suggestion
      await spawn(commandString, [], {
```

**Review by schaable — APPROVED** [review]
