### PR TITLE
Use random non-nested temp dirs during compilation

### LINKED ISSUE #7161: `hh compile` fails without detailed error message if `/tmp/hardhat-solc` is not writable
### Version of Hardhat

3.0.0-next.29

### What happened?

`npx hardhat compile` fails with a nondescriptive error message if `/tmp/hardhat-solc` is not writable.

The `spawnCompile()` function creates the folder, resulting it being owned by the current user.
If another user attempts compilation while the folder exists, it throws an error.
https://github.com/NomicFoundation/hardhat/blob/58a959853cccc037b3184d24d75525d5b4a58784/v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts#L50-L58

`mkdir()` by default does create folders with mode `777`, but since the default umask is `022`, it results in a folder with `755`
(https://github.com/nodejs/node/issues/15092)
This can be fixed by explicitly using `chmod()` to set the permission after creation.

### Minimal reproduction steps

On a system that has more than one user:
1. compile project as user a
   ```sh
   sudo su user-a
   npx hardhat compile
   ```
2. switch to user b
   ```sh
   sudo su user-b
   ```
3. attempt to compile project as user b
   ```console
   $ npx hardhat compile
   Compiling your Solidity contracts...
   Error HHE907: A native version of solc failed to run.

   If you are running MacOS, try installing Apple Rosetta.

   If this error persists, run "npx hardhat clean --global".
   ```

### Search terms

compile error, /tmp/hardhat-solc not writable

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #7161.

See comments inline.

### CODE REVIEW

File: v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts [hunk 1]
```diff
@@ -54,8 +54,7 @@ async function spawnCompile(
 ): Promise<CompilerOutput> {
   // We create a temporary folder to store the output of the compiler in
   // We use a random UUID to avoid collisions with other compilations
-  const tmpFolder = path.join(os.tmpdir(), "hardhat-solc", crypto.randomUUID());
-  await mkdir(tmpFolder);
+  const tmpFolder = await mkdtemp("hardhat-solc-");
```
Comment (fvictorio) [inline v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts:57]: This technically increases the chances of collision, but 6 alphanumerical characters still mean 56_800_235_584 combinations. I think it's fine for the use case.

File: v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts [hunk 2]
```diff
@@ -177,8 +176,7 @@ export class NativeCompiler implements Compiler {
         args.push("--no-import-callback");
       } else if (semver.gte(this.version, "0.6.9")) {
         // version >= 0.6.9
-        const tmpFolder = path.join(os.tmpdir(), "hardhat-solc");
-        await mkdir(tmpFolder);
+        const tmpFolder = await mkdtemp("hardhat-solc-");
```
Comment (fvictorio) [inline v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts:179]: I also made this change because the assumption here is that `tmpFolder` is empty, but the other part of the code was creating directories under `/tmp/hardhat-solc`. While unlikely to be a problem in practice, I still think it's better to just use a unique random empty directory each time.

**Comment by alcuadrado** [comment]
Adding this to the merge queue as franco is OOO
