### PR TITLE
fix: hardhat-chai-matchers - add check byte32 string to reverted matcher

### LINKED ISSUE #4725: [hardhat-chai-matchers] Edge case with `not.to.be.reverted` and view functions
### Version of Hardhat

hardhat-chai-matchers 2.0.3 / hardhat-ethers 3.0.5

### What happened?

The (not) `reverted` matcher throws an error when calling a `view` function returning ``bytes32` that does not revert.

This is because the code inside `expect` actually returns a string, and `reverted.ts` interprets that return value as a hash. Then, when it tries to get the transaction receipt it fails at [this line](https://github.com/NomicFoundation/hardhat/blob/%40nomicfoundation/hardhat-chai-matchers%402.0.3/packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts#L37).

Tested with latest tag `2.0.3`. Probably also happens with other types that can be interpreted as a hash?

### Minimal reproduction steps

Suppose I have library with a view function that doesn't revert, but returns `bytes32`:

Solidity:
```
contract Test {
    bytes32 private _value;

    function setValue(bytes32 value) external {
        _value = value;
    }

    function getValueBytes32() external view returns (bytes32) {
        return _value;
    }

    function getValueUint() external view returns (uint256) {
        return uint256(_value);
    }
}
```

Test:

```
it('is ok', async () => {
    await expect(test.getValueUint()).not.to.be.reverted;
});

it('throws', async () => {
    await expect(test.getValueBytes32()).not.to.be.reverted;
});
```

The error in the second scenario is:
```
HardhatChaiMatchersAssertionError: Assertion error: receipt should not be null
```

A simple workaround is to just not use `expect` in these cases:

```
it('is ok as a workaround', async () => {
    test.getValueBytes32(); // does not revert
});
```

But ideally `not.reverted` should work as with non-view functions and the other return values.

### Search terms

chai-matchers, not.to.be.reverted

### PR DESCRIPTION
**Pull request by iosh**
- [x] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

 Add when receipt is null, check if value is a byte32 string. minimal changes were in PRto resolve #4725 

I see the following comment in the code

```js

        // If the subject of the assertion is not connected to a transaction
        // (hash, receipt, etc.), then the assertion fails.
        // Since we use `false` here, this means that `.not.to.be.reverted`
        // assertions will pass instead of always throwing a validation error.
        // This allows users to do things like:
        //   `expect(c.callStatic.f()).to.not.be.reverted`
        assert(false, "Expected transaction to be reverted");
```

So i think maybe we can change the check to :

```js
      if (
        isTransactionResponse(value) ||
        (typeof value === "string" && isValidTransactionHash(value))
      ) {
        const hash = typeof value === "string" ? value : value.hash;

        // if (!isValidTransactionHash(hash)) {
        //   throw new TypeError(
        //     `Expected a valid transaction hash, but got '${hash}'`
        //   );
        // }

```
This way, we can enable other data types to pass the test, but they will be broken change.

### CODE REVIEW

File: packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts [hunk 1]
```diff
@@ -36,6 +40,14 @@ export function supportReverted(
 
         const receipt = await getTransactionReceipt(hash);
 
+        if (receipt === null) {
+          // If the receipt is null, maybe the string is a bytes32 string
+          if (isByte32String(hash)) {
+            assert(false, "Expected transaction to be reverted");
```
Comment (iosh) [inline packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts:46]: I think it also can throw an error:
```js
 throw new TypeError(
            `Expected a valid transaction hash, but got bytes32  '${hash}'`
       )
```

**Review by schaable — APPROVED** [review]
Looks good. Tested with the code example provided in the issue and it works. Thanks @iosh!
